-- __table__: owned resource generated by `pnpm new:resource`.
-- Ownership comes from the auth.uid() column default and is not grantable to
-- the client, so a forged user_id in a request body cannot take effect.

create table public.__table__ (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title      text not null check (char_length(title) between 1 and 200),
  body       text not null default '' check (char_length(body) <= 10000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.__table__ is 'Owned resource. Ownership is set by the auth.uid() column default, never by the client.';

create index __table___user_id_created_at_idx on public.__table__ (user_id, created_at desc);

create trigger __table___set_updated_at
  before update on public.__table__
  for each row execute function private.set_updated_at();

-- ---------------------------------------------------------------------------
-- Privileges. user_id is absent from the INSERT and UPDATE grants on purpose.
-- ---------------------------------------------------------------------------
revoke all on public.__table__ from anon, authenticated;
grant select on public.__table__ to authenticated;
grant insert (title, body) on public.__table__ to authenticated;
grant update (title, body) on public.__table__ to authenticated;
grant delete on public.__table__ to authenticated;

-- ---------------------------------------------------------------------------
-- RLS: default deny, one policy per operation, ownership from auth.uid().
-- ---------------------------------------------------------------------------
alter table public.__table__ enable row level security;
alter table public.__table__ force row level security;

create policy __table___select_own on public.__table__
  for select to authenticated
  using (user_id = (select auth.uid()));

create policy __table___insert_own on public.__table__
  for insert to authenticated
  with check (user_id = (select auth.uid()));

create policy __table___update_own on public.__table__
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy __table___delete_own on public.__table__
  for delete to authenticated
  using (user_id = (select auth.uid()));

-- Admins read everything, and only read. Delete this policy if admins have no
-- business seeing this table.
create policy __table___select_admin on public.__table__
  for select to authenticated
  using (private.is_admin());
