/**
 * Generates REPOMAP.md: one line per source file with its purpose (taken from
 * the docblock at the top of the file) and its exported symbols.
 * An agent reads this instead of globbing the repo and opening files.
 */
import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const ROOT = process.cwd();
const ROOTS = ['src', 'scripts', 'supabase/migrations', 'tests'];
const OUT = join(ROOT, 'REPOMAP.md');
const GRAPH_MARKER = '<!-- graph -->';

type Entry = { path: string; purpose: string; exports: string[] };

function walk(dir: string, out: string[] = []): string[] {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (/\.(ts|tsx|sql|css)$/.test(name)) out.push(full);
  }
  return out;
}

/** First block comment or `--` header in the file, flattened to one line. */
function readPurpose(source: string, isSql: boolean): string {
  if (isSql) {
    const lines: string[] = [];
    for (const line of source.split('\n')) {
      const match = /^--\s?(.*)$/.exec(line.trim());
      if (!match) break;
      if (/^-{3,}$/.test(match[1].trim())) break;
      lines.push(match[1].trim());
    }
    return lines.join(' ').trim() || '(no docblock)';
  }

  const match = /^\s*\/\*\*([\s\S]*?)\*\//.exec(source);
  if (!match) return '(no docblock)';
  return match[1]
    .split('\n')
    .map((line) => line.replace(/^\s*\*ic?\s?/, '').replace(/^\s*\*\s?/, '').trim())
    .filter(Boolean)
    .join(' ')
    .trim();
}

function readExports(source: string): string[] {
  const names = new Set<string>();
  const patterns = [
    /export\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)/g,
    /export\s+(?:const|let|class)\s+([A-Za-z0-9_]+)/g,
    /export\s+(?:type|interface)\s+([A-Za-z0-9_]+)/g,
    /export\s+default\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)/g,
  ];

  for (const pattern of patterns) {
    for (const match of source.matchAll(pattern)) names.add(match[1]);
  }
  if (/export\s+default\s/.test(source) && !/export\s+default\s+(?:async\s+)?function\s+\w/.test(source)) {
    names.add('default');
  }
  return [...names].sort();
}

const entries: Entry[] = [];

for (const root of ROOTS) {
  for (const file of walk(join(ROOT, root))) {
    const source = readFileSync(file, 'utf8');
    const path = relative(ROOT, file).split(sep).join('/');
    const isSql = path.endsWith('.sql');
    entries.push({
      path,
      purpose: readPurpose(source, isSql),
      exports: isSql || path.endsWith('.css') ? [] : readExports(source),
    });
  }
}

const byDirectory = new Map<string, Entry[]>();
for (const entry of entries) {
  const directory = entry.path.split('/').slice(0, -1).join('/');
  const bucket = byDirectory.get(directory) ?? [];
  bucket.push(entry);
  byDirectory.set(directory, bucket);
}

// Preserve whatever pnpm graph last wrote into the dependency-graph section.
let graphSection = `${GRAPH_MARKER}\n\n_Run \`pnpm graph\` to populate this section._\n`;
if (existsSync(OUT)) {
  const previous = readFileSync(OUT, 'utf8');
  const index = previous.indexOf(GRAPH_MARKER);
  if (index !== -1) graphSection = previous.slice(index);
}

const lines: string[] = [
  '# REPOMAP',
  '',
  '_Generated by `pnpm map`. Do not edit by hand._',
  '',
  'One line per file: path, what it is for, and what it exports. Read this',
  'instead of listing directories and opening files.',
  '',
  `${entries.length} files.`,
  '',
];

for (const directory of [...byDirectory.keys()].sort()) {
  lines.push(`## ${directory}/`, '');
  for (const entry of byDirectory.get(directory)!) {
    const name = entry.path.split('/').pop();
    const exported = entry.exports.length > 0 ? ` — exports: \`${entry.exports.join('`, `')}\`` : '';
    lines.push(`- **${name}** — ${entry.purpose}${exported}`);
  }
  lines.push('');
}

lines.push('## Dependency graph', '');
writeFileSync(OUT, `${lines.join('\n')}${graphSection}`);
console.log(`map    ok    ${entries.length} files -> REPOMAP.md`);
