/**
 * Builds the module dependency graph with madge, fails on any circular
 * dependency, and writes a text summary into the graph section of REPOMAP.md.
 */
import madge from 'madge';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const OUT = join(ROOT, 'REPOMAP.md');
const MARKER = '<!-- graph -->';

async function main() {
  const result = await madge('src', {
    baseDir: ROOT,
    fileExtensions: ['ts', 'tsx'],
    tsConfig: join(ROOT, 'tsconfig.json'),
    detectiveOptions: { ts: { skipTypeImports: true }, tsx: { skipTypeImports: true } },
  });

  const graph = result.obj();
  const circular = result.circular();
  const orphans = result.orphans();

  // Fan-in: which modules everything depends on. These are the files an agent
  // must read before changing anything, so they belong at the top of the map.
  const fanIn = new Map<string, number>();
  for (const dependencies of Object.values(graph)) {
    for (const dependency of dependencies) {
      fanIn.set(dependency, (fanIn.get(dependency) ?? 0) + 1);
    }
  }

  const hubs = [...fanIn.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 12);

  const moduleCount = Object.keys(graph).length;
  const edgeCount = Object.values(graph).reduce((total, list) => total + list.length, 0);

  const lines: string[] = [
    MARKER,
    '',
    '_Generated by `pnpm graph`. Do not edit by hand._',
    '',
    `| metric | value |`,
    `| --- | --- |`,
    `| modules | ${moduleCount} |`,
    `| edges | ${edgeCount} |`,
    `| circular dependencies | ${circular.length} |`,
    `| orphans | ${orphans.length} |`,
    '',
    '### Most depended-on modules',
    '',
    'Change one of these and you change the whole app. Read them first.',
    '',
  ];

  for (const [module, count] of hubs) {
    lines.push(`- \`${module}\` — imported by ${count}`);
  }

  if (orphans.length > 0) {
    lines.push('', '### Orphans', '', 'Reachable from no other module (entry points and pages are expected here).', '');
    for (const orphan of orphans.slice(0, 20)) lines.push(`- \`${orphan}\``);
  }

  lines.push('');

  const previous = readFileSync(OUT, 'utf8');
  const index = previous.indexOf(MARKER);
  const head = index === -1 ? `${previous}\n` : previous.slice(0, index);
  writeFileSync(OUT, head + lines.join('\n'));

  if (circular.length > 0) {
    console.error(`graph  FAIL  ${circular.length} circular dependency chain(s)`);
    for (const chain of circular) console.error(`  ${chain.join(' -> ')}`);
    console.error('  Break the cycle by moving the shared type or helper into its own file.');
    process.exit(1);
  }

  console.log(`graph  ok    ${moduleCount} modules, ${edgeCount} edges, 0 cycles -> REPOMAP.md`);
}

main().catch((error) => {
  console.error('graph  ERROR', error instanceof Error ? error.message : error);
  process.exit(1);
});
